### ISSUE TITLE
Equity fonts in repo

### ISSUE THREAD

**Issue by mbutterick** [vdavez/website#5]
I know you have a paid license for my fonts (thank you) but I'm afraid the license doesn't permit public redistribution of the fonts through a GitHub repo.

**Comment by vzvenyach** [comment]
Eek. Hmmm... Any suggestions on how to refactor? Would it be acceptable to load them from an S3 bucket instead?

**Comment by mbutterick** [comment]
Loading them from S3 is fine. Alternatively, fold them into the CSS file as base64-encoded data.
